#include "DispatchInstall.h"

#include "../runtime/AppGLRuntime.h"

namespace appgl {

void installBootstrapDispatch(GLDispatchTable& dispatch, CoverageStore& coverage) {
    dispatch.glClearColor = &impl::glClearColor;
    dispatch.glClear = &impl::glClear;
    dispatch.glClearDepth = &impl::glClearDepth;
    dispatch.glClearStencil = &impl::glClearStencil;
    dispatch.glViewport = &impl::glViewport;
    dispatch.glFlush = &impl::glFlush;
    dispatch.glReadPixels = &impl::glReadPixels;
    dispatch.glGetBooleanv = &impl::glGetBooleanv;
    dispatch.glGetIntegerv = &impl::glGetIntegerv;
    dispatch.glGetInteger64v = &impl::glGetInteger64v;
    dispatch.glGetFloatv = &impl::glGetFloatv;
    dispatch.glGetDoublev = &impl::glGetDoublev;
    dispatch.glGenBuffers = &impl::glGenBuffers;
    dispatch.glDeleteBuffers = &impl::glDeleteBuffers;
    dispatch.glIsBuffer = &impl::glIsBuffer;
    dispatch.glBindBuffer = &impl::glBindBuffer;
    dispatch.glBindBufferBase = &impl::glBindBufferBase;
    dispatch.glBindBufferRange = &impl::glBindBufferRange;
    dispatch.glBufferData = &impl::glBufferData;
    dispatch.glBufferSubData = &impl::glBufferSubData;
    dispatch.glCopyBufferSubData = &impl::glCopyBufferSubData;
    dispatch.glGetBufferSubData = &impl::glGetBufferSubData;
    dispatch.glMapBuffer = &impl::glMapBuffer;
    dispatch.glMapBufferRange = &impl::glMapBufferRange;
    dispatch.glUnmapBuffer = &impl::glUnmapBuffer;
    dispatch.glFlushMappedBufferRange = &impl::glFlushMappedBufferRange;
    dispatch.glGetBufferParameteriv = &impl::glGetBufferParameteriv;
    dispatch.glGetBufferParameteri64v = &impl::glGetBufferParameteri64v;
    dispatch.glGetBufferPointerv = &impl::glGetBufferPointerv;
    dispatch.glGenVertexArrays = &impl::glGenVertexArrays;
    dispatch.glDeleteVertexArrays = &impl::glDeleteVertexArrays;
    dispatch.glIsVertexArray = &impl::glIsVertexArray;
    dispatch.glBindVertexArray = &impl::glBindVertexArray;
    dispatch.glEnableVertexAttribArray = &impl::glEnableVertexAttribArray;
    dispatch.glDisableVertexAttribArray = &impl::glDisableVertexAttribArray;
    dispatch.glVertexAttribPointer = &impl::glVertexAttribPointer;
    dispatch.glVertexAttribIPointer = &impl::glVertexAttribIPointer;
    dispatch.glVertexAttribDivisor = &impl::glVertexAttribDivisor;
    dispatch.glGetVertexAttribiv = &impl::glGetVertexAttribiv;
    dispatch.glGetVertexAttribfv = &impl::glGetVertexAttribfv;
    dispatch.glGetVertexAttribPointerv = &impl::glGetVertexAttribPointerv;
    dispatch.glEnable = &impl::glEnable;
    dispatch.glDisable = &impl::glDisable;
    dispatch.glIsEnabled = &impl::glIsEnabled;
    dispatch.glScissor = &impl::glScissor;
    dispatch.glDepthRange = &impl::glDepthRange;
    dispatch.glDepthRangef = &impl::glDepthRangef;
    dispatch.glBlendFunc = &impl::glBlendFunc;
    dispatch.glBlendFuncSeparate = &impl::glBlendFuncSeparate;
    dispatch.glBlendEquation = &impl::glBlendEquation;
    dispatch.glBlendEquationSeparate = &impl::glBlendEquationSeparate;
    dispatch.glBlendColor = &impl::glBlendColor;
    dispatch.glColorMask = &impl::glColorMask;
    dispatch.glColorMaski = &impl::glColorMaski;
    dispatch.glDepthFunc = &impl::glDepthFunc;
    dispatch.glDepthMask = &impl::glDepthMask;
    dispatch.glStencilFunc = &impl::glStencilFunc;
    dispatch.glStencilFuncSeparate = &impl::glStencilFuncSeparate;
    dispatch.glStencilOp = &impl::glStencilOp;
    dispatch.glStencilOpSeparate = &impl::glStencilOpSeparate;
    dispatch.glStencilMask = &impl::glStencilMask;
    dispatch.glStencilMaskSeparate = &impl::glStencilMaskSeparate;
    dispatch.glCullFace = &impl::glCullFace;
    dispatch.glFrontFace = &impl::glFrontFace;
    dispatch.glPolygonOffset = &impl::glPolygonOffset;
    dispatch.glLineWidth = &impl::glLineWidth;
    dispatch.glPointSize = &impl::glPointSize;
    dispatch.glHint = &impl::glHint;
    dispatch.glGetString = &impl::glGetString;
    dispatch.glGetError = &impl::glGetError;
    dispatch.glDebugMessageControl = &impl::glDebugMessageControl;
    dispatch.glDebugMessageInsert = &impl::glDebugMessageInsert;
    dispatch.glDebugMessageCallback = &impl::glDebugMessageCallback;
    dispatch.glGetDebugMessageLog = &impl::glGetDebugMessageLog;
    dispatch.glPushDebugGroup = &impl::glPushDebugGroup;
    dispatch.glPopDebugGroup = &impl::glPopDebugGroup;
    dispatch.glObjectLabel = &impl::glObjectLabel;
    dispatch.glGetObjectLabel = &impl::glGetObjectLabel;
    dispatch.glObjectPtrLabel = &impl::glObjectPtrLabel;
    dispatch.glGetObjectPtrLabel = &impl::glGetObjectPtrLabel;
    dispatch.glGetPointerv = &impl::glGetPointerv;

    coverage.markImplemented(FunctionId::glClearColor, "Bootstrap clear-color plumbing is live.");
    coverage.markImplemented(FunctionId::glClear, "Bootstrap Metal clear path is live.");
    coverage.markImplemented(FunctionId::glClearDepth, "Default framebuffer depth clear state is live.");
    coverage.markImplemented(FunctionId::glClearStencil, "Default framebuffer stencil clear state is live.");
    coverage.markImplemented(FunctionId::glViewport, "Bootstrap viewport path is live.");
    coverage.markImplemented(FunctionId::glFlush, "Bootstrap flush path is live.");
    coverage.markImplemented(FunctionId::glReadPixels, "RGBA/UNSIGNED_BYTE readback is live for gauntlet captures.");
    coverage.markImplemented(FunctionId::glGetBooleanv, "Boolean state/capability query routing is live.");
    coverage.markImplemented(FunctionId::glGetIntegerv, "Capability integer query routing is live.");
    coverage.markImplemented(FunctionId::glGetInteger64v, "Capability integer64 query routing is live.");
    coverage.markImplemented(FunctionId::glGetFloatv, "Capability float query routing is live.");
    coverage.markImplemented(FunctionId::glGetDoublev, "Double state/capability query routing is live.");
    coverage.markImplemented(FunctionId::glGenBuffers, "Buffer name generation is live.");
    coverage.markImplemented(FunctionId::glDeleteBuffers, "Buffer deletion is live.");
    coverage.markImplemented(FunctionId::glIsBuffer, "Buffer object query is live.");
    coverage.markImplemented(FunctionId::glBindBuffer, "Generic buffer binding is live.");
    coverage.markImplemented(FunctionId::glBindBufferBase, "Indexed buffer-base binding is live.");
    coverage.markImplemented(FunctionId::glBindBufferRange, "Indexed buffer-range binding is live.");
    coverage.markImplemented(FunctionId::glBufferData, "Buffer storage allocation is live.");
    coverage.markImplemented(FunctionId::glBufferSubData, "Buffer subdata update is live.");
    coverage.markImplemented(FunctionId::glCopyBufferSubData, "Buffer copy is live.");
    coverage.markImplemented(FunctionId::glGetBufferSubData, "Buffer readback is live.");
    coverage.markImplemented(FunctionId::glMapBuffer, "Whole-buffer mapping is live.");
    coverage.markImplemented(FunctionId::glMapBufferRange, "Mapped buffer ranges are live.");
    coverage.markImplemented(FunctionId::glUnmapBuffer, "Mapped buffer unmap is live.");
    coverage.markImplemented(FunctionId::glFlushMappedBufferRange, "Explicit mapped-range flush is live.");
    coverage.markImplemented(FunctionId::glGetBufferParameteriv, "Buffer parameter query is live.");
    coverage.markImplemented(FunctionId::glGetBufferParameteri64v, "Buffer parameter query is live.");
    coverage.markImplemented(FunctionId::glGetBufferPointerv, "Mapped buffer pointer query is live.");
    coverage.markImplemented(FunctionId::glGenVertexArrays, "Vertex-array name generation is live.");
    coverage.markImplemented(FunctionId::glDeleteVertexArrays, "Vertex-array deletion is live.");
    coverage.markImplemented(FunctionId::glIsVertexArray, "Vertex-array object query is live.");
    coverage.markImplemented(FunctionId::glBindVertexArray, "Vertex-array binding is live.");
    coverage.markImplemented(FunctionId::glEnableVertexAttribArray, "Vertex attribute enable state is live.");
    coverage.markImplemented(FunctionId::glDisableVertexAttribArray, "Vertex attribute disable state is live.");
    coverage.markImplemented(FunctionId::glVertexAttribPointer, "Floating-point vertex attribute pointer state is live.");
    coverage.markImplemented(FunctionId::glVertexAttribIPointer, "Integer vertex attribute pointer state is live.");
    coverage.markImplemented(FunctionId::glVertexAttribDivisor, "Vertex attribute divisor state is live.");
    coverage.markImplemented(FunctionId::glGetVertexAttribiv, "Integer vertex attribute state query is live.");
    coverage.markImplemented(FunctionId::glGetVertexAttribfv, "Float vertex attribute state query is live.");
    coverage.markImplemented(FunctionId::glGetVertexAttribPointerv, "Vertex attribute pointer query is live.");
    coverage.markImplemented(FunctionId::glEnable, "Enable-state tracking is live.");
    coverage.markImplemented(FunctionId::glDisable, "Enable-state tracking is live.");
    coverage.markImplemented(FunctionId::glIsEnabled, "Enable-state query is live.");
    coverage.markImplemented(FunctionId::glScissor, "Scissor-box tracking is live.");
    coverage.markImplemented(FunctionId::glDepthRange, "Depth-range tracking is live.");
    coverage.markImplemented(FunctionId::glDepthRangef, "Depth-range float alias is live.");
    coverage.markImplemented(FunctionId::glBlendFunc, "Blend function tracking is live.");
    coverage.markImplemented(FunctionId::glBlendFuncSeparate, "Separate blend function tracking is live.");
    coverage.markImplemented(FunctionId::glBlendEquation, "Blend equation tracking is live.");
    coverage.markImplemented(FunctionId::glBlendEquationSeparate, "Separate blend equation tracking is live.");
    coverage.markImplemented(FunctionId::glBlendColor, "Constant blend color tracking is live.");
    coverage.markImplemented(FunctionId::glColorMask, "Color write-mask tracking is live.");
    coverage.markImplemented(FunctionId::glColorMaski, "Indexed color write-mask tracking is live.");
    coverage.markImplemented(FunctionId::glDepthFunc, "Depth compare tracking is live.");
    coverage.markImplemented(FunctionId::glDepthMask, "Depth write-mask tracking is live.");
    coverage.markImplemented(FunctionId::glStencilFunc, "Stencil compare tracking is live.");
    coverage.markImplemented(FunctionId::glStencilFuncSeparate, "Separate stencil compare tracking is live.");
    coverage.markImplemented(FunctionId::glStencilOp, "Stencil operation tracking is live.");
    coverage.markImplemented(FunctionId::glStencilOpSeparate, "Separate stencil operation tracking is live.");
    coverage.markImplemented(FunctionId::glStencilMask, "Stencil write-mask tracking is live.");
    coverage.markImplemented(FunctionId::glStencilMaskSeparate, "Separate stencil write-mask tracking is live.");
    coverage.markImplemented(FunctionId::glCullFace, "Cull-face tracking is live.");
    coverage.markImplemented(FunctionId::glFrontFace, "Front-face winding tracking is live.");
    coverage.markImplemented(FunctionId::glPolygonOffset, "Polygon offset tracking is live.");
    coverage.markImplemented(FunctionId::glLineWidth, "Line-width tracking is live.");
    coverage.markImplemented(FunctionId::glPointSize, "Point-size tracking is live.");
    coverage.markImplemented(FunctionId::glHint, "Hint-state tracking is live.");
    coverage.markImplemented(FunctionId::glGetString, "Bootstrap identity reporting is live.");
    coverage.markImplemented(FunctionId::glGetError, "Bootstrap per-context error FIFO is live.");
    coverage.markImplemented(FunctionId::glDebugMessageControl, "Debug message filtering is live.");
    coverage.markImplemented(FunctionId::glDebugMessageInsert, "Debug message insertion is live.");
    coverage.markImplemented(FunctionId::glDebugMessageCallback, "Debug callback plumbing is live.");
    coverage.markImplemented(FunctionId::glGetDebugMessageLog, "Debug message log retrieval is live.");
    coverage.markImplemented(FunctionId::glPushDebugGroup, "Debug group push is live.");
    coverage.markImplemented(FunctionId::glPopDebugGroup, "Debug group pop is live.");
    coverage.markImplemented(FunctionId::glObjectLabel, "Debug object labels are live.");
    coverage.markImplemented(FunctionId::glGetObjectLabel, "Debug object-label queries are live.");
    coverage.markImplemented(FunctionId::glObjectPtrLabel, "Debug pointer labels are live.");
    coverage.markImplemented(FunctionId::glGetObjectPtrLabel, "Debug pointer-label queries are live.");
    coverage.markImplemented(FunctionId::glGetPointerv, "Debug pointer queries are live.");
}

}  // namespace appgl
