#include "DispatchInstall.h"

#include "../runtime/AppGLRuntime.h"

namespace appgl {

void installBootstrapDispatch(GLDispatchTable& dispatch, CoverageStore& coverage) {
    dispatch.glClearColor = &impl::glClearColor;
    dispatch.glDrawBuffer = &impl::glDrawBuffer;
    dispatch.glClear = &impl::glClear;
    dispatch.glClearDepth = &impl::glClearDepth;
    dispatch.glClearStencil = &impl::glClearStencil;
    dispatch.glViewport = &impl::glViewport;
    dispatch.glFlush = &impl::glFlush;
    dispatch.glReadPixels = &impl::glReadPixels;
    dispatch.glGetBooleanv = &impl::glGetBooleanv;
    dispatch.glGetIntegerv = &impl::glGetIntegerv;
    dispatch.glGetInteger64v = &impl::glGetInteger64v;
    dispatch.glGetFloatv = &impl::glGetFloatv;
    dispatch.glGetDoublev = &impl::glGetDoublev;
    dispatch.glGenBuffers = &impl::glGenBuffers;
    dispatch.glDeleteBuffers = &impl::glDeleteBuffers;
    dispatch.glIsBuffer = &impl::glIsBuffer;
    dispatch.glBindBuffer = &impl::glBindBuffer;
    dispatch.glBindBufferBase = &impl::glBindBufferBase;
    dispatch.glBindBufferRange = &impl::glBindBufferRange;
    dispatch.glBufferData = &impl::glBufferData;
    dispatch.glBufferSubData = &impl::glBufferSubData;
    dispatch.glCopyBufferSubData = &impl::glCopyBufferSubData;
    dispatch.glGetBufferSubData = &impl::glGetBufferSubData;
    dispatch.glMapBuffer = &impl::glMapBuffer;
    dispatch.glMapBufferRange = &impl::glMapBufferRange;
    dispatch.glUnmapBuffer = &impl::glUnmapBuffer;
    dispatch.glFlushMappedBufferRange = &impl::glFlushMappedBufferRange;
    dispatch.glGetBufferParameteriv = &impl::glGetBufferParameteriv;
    dispatch.glGetBufferParameteri64v = &impl::glGetBufferParameteri64v;
    dispatch.glGetBufferPointerv = &impl::glGetBufferPointerv;
    dispatch.glGenVertexArrays = &impl::glGenVertexArrays;
    dispatch.glDeleteVertexArrays = &impl::glDeleteVertexArrays;
    dispatch.glIsVertexArray = &impl::glIsVertexArray;
    dispatch.glBindVertexArray = &impl::glBindVertexArray;
    dispatch.glEnableVertexAttribArray = &impl::glEnableVertexAttribArray;
    dispatch.glDisableVertexAttribArray = &impl::glDisableVertexAttribArray;
    dispatch.glVertexAttribPointer = &impl::glVertexAttribPointer;
    dispatch.glVertexAttribIPointer = &impl::glVertexAttribIPointer;
    dispatch.glVertexAttribDivisor = &impl::glVertexAttribDivisor;
    dispatch.glGetVertexAttribiv = &impl::glGetVertexAttribiv;
    dispatch.glGetVertexAttribfv = &impl::glGetVertexAttribfv;
    dispatch.glGetVertexAttribPointerv = &impl::glGetVertexAttribPointerv;
    dispatch.glActiveTexture = &impl::glActiveTexture;
    dispatch.glGenTextures = &impl::glGenTextures;
    dispatch.glDeleteTextures = &impl::glDeleteTextures;
    dispatch.glIsTexture = &impl::glIsTexture;
    dispatch.glBindTexture = &impl::glBindTexture;
    dispatch.glTexImage1D = &impl::glTexImage1D;
    dispatch.glTexImage2D = &impl::glTexImage2D;
    dispatch.glTexImage3D = &impl::glTexImage3D;
    dispatch.glTexSubImage1D = &impl::glTexSubImage1D;
    dispatch.glTexSubImage2D = &impl::glTexSubImage2D;
    dispatch.glTexSubImage3D = &impl::glTexSubImage3D;
    dispatch.glTexParameteri = &impl::glTexParameteri;
    dispatch.glTexParameteriv = &impl::glTexParameteriv;
    dispatch.glTexParameterf = &impl::glTexParameterf;
    dispatch.glTexParameterfv = &impl::glTexParameterfv;
    dispatch.glTexParameterIiv = &impl::glTexParameterIiv;
    dispatch.glTexParameterIuiv = &impl::glTexParameterIuiv;
    dispatch.glGetTexParameteriv = &impl::glGetTexParameteriv;
    dispatch.glGetTexParameterfv = &impl::glGetTexParameterfv;
    dispatch.glGetTexParameterIiv = &impl::glGetTexParameterIiv;
    dispatch.glGetTexParameterIuiv = &impl::glGetTexParameterIuiv;
    dispatch.glGenerateMipmap = &impl::glGenerateMipmap;
    dispatch.glPixelStorei = &impl::glPixelStorei;
    dispatch.glPixelStoref = &impl::glPixelStoref;
    dispatch.glReadBuffer = &impl::glReadBuffer;
    dispatch.glDrawBuffers = &impl::glDrawBuffers;
    dispatch.glIsRenderbuffer = &impl::glIsRenderbuffer;
    dispatch.glBindRenderbuffer = &impl::glBindRenderbuffer;
    dispatch.glDeleteRenderbuffers = &impl::glDeleteRenderbuffers;
    dispatch.glGenRenderbuffers = &impl::glGenRenderbuffers;
    dispatch.glRenderbufferStorage = &impl::glRenderbufferStorage;
    dispatch.glGetRenderbufferParameteriv = &impl::glGetRenderbufferParameteriv;
    dispatch.glGenFramebuffers = &impl::glGenFramebuffers;
    dispatch.glDeleteFramebuffers = &impl::glDeleteFramebuffers;
    dispatch.glIsFramebuffer = &impl::glIsFramebuffer;
    dispatch.glBindFramebuffer = &impl::glBindFramebuffer;
    dispatch.glCheckFramebufferStatus = &impl::glCheckFramebufferStatus;
    dispatch.glFramebufferTexture1D = &impl::glFramebufferTexture1D;
    dispatch.glFramebufferTexture2D = &impl::glFramebufferTexture2D;
    dispatch.glFramebufferTexture3D = &impl::glFramebufferTexture3D;
    dispatch.glFramebufferRenderbuffer = &impl::glFramebufferRenderbuffer;
    dispatch.glBlitFramebuffer = &impl::glBlitFramebuffer;
    dispatch.glGetFramebufferAttachmentParameteriv = &impl::glGetFramebufferAttachmentParameteriv;
    dispatch.glRenderbufferStorageMultisample = &impl::glRenderbufferStorageMultisample;
    dispatch.glFramebufferTextureLayer = &impl::glFramebufferTextureLayer;
    dispatch.glFramebufferTexture = &impl::glFramebufferTexture;
    dispatch.glGenSamplers = &impl::glGenSamplers;
    dispatch.glDeleteSamplers = &impl::glDeleteSamplers;
    dispatch.glIsSampler = &impl::glIsSampler;
    dispatch.glBindSampler = &impl::glBindSampler;
    dispatch.glSamplerParameteri = &impl::glSamplerParameteri;
    dispatch.glSamplerParameteriv = &impl::glSamplerParameteriv;
    dispatch.glSamplerParameterf = &impl::glSamplerParameterf;
    dispatch.glSamplerParameterfv = &impl::glSamplerParameterfv;
    dispatch.glSamplerParameterIiv = &impl::glSamplerParameterIiv;
    dispatch.glSamplerParameterIuiv = &impl::glSamplerParameterIuiv;
    dispatch.glGetSamplerParameteriv = &impl::glGetSamplerParameteriv;
    dispatch.glGetSamplerParameterfv = &impl::glGetSamplerParameterfv;
    dispatch.glGetSamplerParameterIiv = &impl::glGetSamplerParameterIiv;
    dispatch.glGetSamplerParameterIuiv = &impl::glGetSamplerParameterIuiv;
    dispatch.glEnable = &impl::glEnable;
    dispatch.glDisable = &impl::glDisable;
    dispatch.glIsEnabled = &impl::glIsEnabled;
    dispatch.glScissor = &impl::glScissor;
    dispatch.glDepthRange = &impl::glDepthRange;
    dispatch.glDepthRangef = &impl::glDepthRangef;
    dispatch.glBlendFunc = &impl::glBlendFunc;
    dispatch.glBlendFuncSeparate = &impl::glBlendFuncSeparate;
    dispatch.glBlendFunci = &impl::glBlendFunci;
    dispatch.glBlendFuncSeparatei = &impl::glBlendFuncSeparatei;
    dispatch.glBlendEquation = &impl::glBlendEquation;
    dispatch.glBlendEquationSeparate = &impl::glBlendEquationSeparate;
    dispatch.glBlendEquationi = &impl::glBlendEquationi;
    dispatch.glBlendEquationSeparatei = &impl::glBlendEquationSeparatei;
    dispatch.glMinSampleShading = &impl::glMinSampleShading;
    dispatch.glBlendColor = &impl::glBlendColor;
    dispatch.glColorMask = &impl::glColorMask;
    dispatch.glColorMaski = &impl::glColorMaski;
    dispatch.glDepthFunc = &impl::glDepthFunc;
    dispatch.glDepthMask = &impl::glDepthMask;
    dispatch.glStencilFunc = &impl::glStencilFunc;
    dispatch.glStencilFuncSeparate = &impl::glStencilFuncSeparate;
    dispatch.glStencilOp = &impl::glStencilOp;
    dispatch.glStencilOpSeparate = &impl::glStencilOpSeparate;
    dispatch.glStencilMask = &impl::glStencilMask;
    dispatch.glStencilMaskSeparate = &impl::glStencilMaskSeparate;
    dispatch.glCullFace = &impl::glCullFace;
    dispatch.glFrontFace = &impl::glFrontFace;
    dispatch.glPolygonOffset = &impl::glPolygonOffset;
    dispatch.glLineWidth = &impl::glLineWidth;
    dispatch.glPointSize = &impl::glPointSize;
    dispatch.glHint = &impl::glHint;
    dispatch.glGetString = &impl::glGetString;
    dispatch.glGetError = &impl::glGetError;
    dispatch.glDebugMessageControl = &impl::glDebugMessageControl;
    dispatch.glDebugMessageInsert = &impl::glDebugMessageInsert;
    dispatch.glDebugMessageCallback = &impl::glDebugMessageCallback;
    dispatch.glGetDebugMessageLog = &impl::glGetDebugMessageLog;
    dispatch.glPushDebugGroup = &impl::glPushDebugGroup;
    dispatch.glPopDebugGroup = &impl::glPopDebugGroup;
    dispatch.glObjectLabel = &impl::glObjectLabel;
    dispatch.glGetObjectLabel = &impl::glGetObjectLabel;
    dispatch.glObjectPtrLabel = &impl::glObjectPtrLabel;
    dispatch.glGetObjectPtrLabel = &impl::glGetObjectPtrLabel;
    dispatch.glGetPointerv = &impl::glGetPointerv;

    dispatch.glCreateShader = &impl::glCreateShader;
    dispatch.glDeleteShader = &impl::glDeleteShader;
    dispatch.glIsShader = &impl::glIsShader;
    dispatch.glShaderSource = &impl::glShaderSource;
    dispatch.glCompileShader = &impl::glCompileShader;
    dispatch.glGetShaderiv = &impl::glGetShaderiv;
    dispatch.glGetShaderInfoLog = &impl::glGetShaderInfoLog;
    dispatch.glGetShaderSource = &impl::glGetShaderSource;
    dispatch.glCreateProgram = &impl::glCreateProgram;
    dispatch.glDeleteProgram = &impl::glDeleteProgram;
    dispatch.glIsProgram = &impl::glIsProgram;
    dispatch.glAttachShader = &impl::glAttachShader;
    dispatch.glDetachShader = &impl::glDetachShader;
    dispatch.glLinkProgram = &impl::glLinkProgram;
    dispatch.glUseProgram = &impl::glUseProgram;
    dispatch.glValidateProgram = &impl::glValidateProgram;
    dispatch.glGetProgramiv = &impl::glGetProgramiv;
    dispatch.glGetProgramInfoLog = &impl::glGetProgramInfoLog;
    dispatch.glGetAttachedShaders = &impl::glGetAttachedShaders;
    dispatch.glBindAttribLocation = &impl::glBindAttribLocation;
    dispatch.glGetAttribLocation = &impl::glGetAttribLocation;
    dispatch.glGetActiveAttrib = &impl::glGetActiveAttrib;
    dispatch.glGetUniformLocation = &impl::glGetUniformLocation;
    dispatch.glGetActiveUniform = &impl::glGetActiveUniform;
    dispatch.glGetUniformfv = &impl::glGetUniformfv;
    dispatch.glGetUniformiv = &impl::glGetUniformiv;
    dispatch.glGetUniformuiv = &impl::glGetUniformuiv;
    dispatch.glUniform1f = &impl::glUniform1f;
    dispatch.glUniform2f = &impl::glUniform2f;
    dispatch.glUniform3f = &impl::glUniform3f;
    dispatch.glUniform4f = &impl::glUniform4f;
    dispatch.glUniform1i = &impl::glUniform1i;
    dispatch.glUniform2i = &impl::glUniform2i;
    dispatch.glUniform3i = &impl::glUniform3i;
    dispatch.glUniform4i = &impl::glUniform4i;
    dispatch.glUniform1ui = &impl::glUniform1ui;
    dispatch.glUniform2ui = &impl::glUniform2ui;
    dispatch.glUniform3ui = &impl::glUniform3ui;
    dispatch.glUniform4ui = &impl::glUniform4ui;
    dispatch.glUniform1fv = &impl::glUniform1fv;
    dispatch.glUniform2fv = &impl::glUniform2fv;
    dispatch.glUniform3fv = &impl::glUniform3fv;
    dispatch.glUniform4fv = &impl::glUniform4fv;
    dispatch.glUniform1iv = &impl::glUniform1iv;
    dispatch.glUniform2iv = &impl::glUniform2iv;
    dispatch.glUniform3iv = &impl::glUniform3iv;
    dispatch.glUniform4iv = &impl::glUniform4iv;
    dispatch.glUniform1uiv = &impl::glUniform1uiv;
    dispatch.glUniform2uiv = &impl::glUniform2uiv;
    dispatch.glUniform3uiv = &impl::glUniform3uiv;
    dispatch.glUniform4uiv = &impl::glUniform4uiv;
    dispatch.glUniformMatrix2fv = &impl::glUniformMatrix2fv;
    dispatch.glUniformMatrix3fv = &impl::glUniformMatrix3fv;
    dispatch.glUniformMatrix4fv = &impl::glUniformMatrix4fv;
    // GL 4.0 double-precision uniform setters (f64→f32 narrowing).
    dispatch.glGetUniformdv = &impl::glGetUniformdv;
    dispatch.glUniform1d = &impl::glUniform1d;
    dispatch.glUniform2d = &impl::glUniform2d;
    dispatch.glUniform3d = &impl::glUniform3d;
    dispatch.glUniform4d = &impl::glUniform4d;
    dispatch.glUniform1dv = &impl::glUniform1dv;
    dispatch.glUniform2dv = &impl::glUniform2dv;
    dispatch.glUniform3dv = &impl::glUniform3dv;
    dispatch.glUniform4dv = &impl::glUniform4dv;
    dispatch.glUniformMatrix2dv = &impl::glUniformMatrix2dv;
    dispatch.glUniformMatrix3dv = &impl::glUniformMatrix3dv;
    dispatch.glUniformMatrix4dv = &impl::glUniformMatrix4dv;
    dispatch.glUniformMatrix2x3dv = &impl::glUniformMatrix2x3dv;
    dispatch.glUniformMatrix2x4dv = &impl::glUniformMatrix2x4dv;
    dispatch.glUniformMatrix3x2dv = &impl::glUniformMatrix3x2dv;
    dispatch.glUniformMatrix3x4dv = &impl::glUniformMatrix3x4dv;
    dispatch.glUniformMatrix4x2dv = &impl::glUniformMatrix4x2dv;
    dispatch.glUniformMatrix4x3dv = &impl::glUniformMatrix4x3dv;
    dispatch.glDrawArrays = &impl::glDrawArrays;
    dispatch.glDrawElements = &impl::glDrawElements;
    // GL 4.0 — tessellation patch parameters (Group 7).
    dispatch.glPatchParameteri = &impl::glPatchParameteri;
    dispatch.glPatchParameterfv = &impl::glPatchParameterfv;
    // GL 4.0 — indexed queries (Group 5).
    dispatch.glBeginQueryIndexed = &impl::glBeginQueryIndexed;
    dispatch.glEndQueryIndexed = &impl::glEndQueryIndexed;
    dispatch.glGetQueryIndexediv = &impl::glGetQueryIndexediv;
    // GL 4.1 — viewport/scissor/depth arrays (Group 8).
    dispatch.glViewportArrayv = &impl::glViewportArrayv;
    dispatch.glViewportIndexedf = &impl::glViewportIndexedf;
    dispatch.glViewportIndexedfv = &impl::glViewportIndexedfv;
    dispatch.glScissorArrayv = &impl::glScissorArrayv;
    dispatch.glScissorIndexed = &impl::glScissorIndexed;
    dispatch.glScissorIndexedv = &impl::glScissorIndexedv;
    dispatch.glDepthRangeArrayv = &impl::glDepthRangeArrayv;
    dispatch.glDepthRangeIndexed = &impl::glDepthRangeIndexed;
    dispatch.glGetFloati_v = &impl::glGetFloati_v;
    dispatch.glGetDoublei_v = &impl::glGetDoublei_v;
    dispatch.glClearDepthf = &impl::glClearDepthf;
    // GL 4.1 — shader precision (Group 13).
    dispatch.glGetShaderPrecisionFormat = &impl::glGetShaderPrecisionFormat;

    coverage.markImplemented(FunctionId::glClearColor, "Bootstrap clear-color plumbing is live.");
    coverage.markImplemented(FunctionId::glDrawBuffer, "Single draw-buffer state tracking is live.");
    coverage.markImplemented(FunctionId::glClear, "Bootstrap Metal clear path is live.");
    coverage.markImplemented(FunctionId::glClearDepth, "Default framebuffer depth clear state is live.");
    coverage.markImplemented(FunctionId::glClearStencil, "Default framebuffer stencil clear state is live.");
    coverage.markImplemented(FunctionId::glViewport, "Bootstrap viewport path is live.");
    coverage.markImplemented(FunctionId::glFlush, "Bootstrap flush path is live.");
    coverage.markImplemented(FunctionId::glReadPixels, "RGBA/UNSIGNED_BYTE readback is live for gauntlet captures.");
    coverage.markImplemented(FunctionId::glGetBooleanv, "Boolean state/capability query routing is live.");
    coverage.markImplemented(FunctionId::glGetIntegerv, "Capability integer query routing is live.");
    coverage.markImplemented(FunctionId::glGetInteger64v, "Capability integer64 query routing is live.");
    coverage.markImplemented(FunctionId::glGetFloatv, "Capability float query routing is live.");
    coverage.markImplemented(FunctionId::glGetDoublev, "Double state/capability query routing is live.");
    coverage.markImplemented(FunctionId::glGenBuffers, "Buffer name generation is live.");
    coverage.markImplemented(FunctionId::glDeleteBuffers, "Buffer deletion is live.");
    coverage.markImplemented(FunctionId::glIsBuffer, "Buffer object query is live.");
    coverage.markImplemented(FunctionId::glBindBuffer, "Generic buffer binding is live.");
    coverage.markImplemented(FunctionId::glBindBufferBase, "Indexed buffer-base binding is live.");
    coverage.markImplemented(FunctionId::glBindBufferRange, "Indexed buffer-range binding is live.");
    coverage.markImplemented(FunctionId::glBufferData, "Buffer storage allocation is live.");
    coverage.markImplemented(FunctionId::glBufferSubData, "Buffer subdata update is live.");
    coverage.markImplemented(FunctionId::glCopyBufferSubData, "Buffer copy is live.");
    coverage.markImplemented(FunctionId::glGetBufferSubData, "Buffer readback is live.");
    coverage.markImplemented(FunctionId::glMapBuffer, "Whole-buffer mapping is live.");
    coverage.markImplemented(FunctionId::glMapBufferRange, "Mapped buffer ranges are live.");
    coverage.markImplemented(FunctionId::glUnmapBuffer, "Mapped buffer unmap is live.");
    coverage.markImplemented(FunctionId::glFlushMappedBufferRange, "Explicit mapped-range flush is live.");
    coverage.markImplemented(FunctionId::glGetBufferParameteriv, "Buffer parameter query is live.");
    coverage.markImplemented(FunctionId::glGetBufferParameteri64v, "Buffer parameter query is live.");
    coverage.markImplemented(FunctionId::glGetBufferPointerv, "Mapped buffer pointer query is live.");
    coverage.markImplemented(FunctionId::glGenVertexArrays, "Vertex-array name generation is live.");
    coverage.markImplemented(FunctionId::glDeleteVertexArrays, "Vertex-array deletion is live.");
    coverage.markImplemented(FunctionId::glIsVertexArray, "Vertex-array object query is live.");
    coverage.markImplemented(FunctionId::glBindVertexArray, "Vertex-array binding is live.");
    coverage.markImplemented(FunctionId::glEnableVertexAttribArray, "Vertex attribute enable state is live.");
    coverage.markImplemented(FunctionId::glDisableVertexAttribArray, "Vertex attribute disable state is live.");
    coverage.markImplemented(FunctionId::glVertexAttribPointer, "Floating-point vertex attribute pointer state is live.");
    coverage.markImplemented(FunctionId::glVertexAttribIPointer, "Integer vertex attribute pointer state is live.");
    coverage.markImplemented(FunctionId::glVertexAttribDivisor, "Vertex attribute divisor state is live.");
    coverage.markImplemented(FunctionId::glGetVertexAttribiv, "Integer vertex attribute state query is live.");
    coverage.markImplemented(FunctionId::glGetVertexAttribfv, "Float vertex attribute state query is live.");
    coverage.markImplemented(FunctionId::glGetVertexAttribPointerv, "Vertex attribute pointer query is live.");
    coverage.markImplemented(FunctionId::glActiveTexture, "Active texture unit tracking is live.");
    coverage.markImplemented(FunctionId::glGenTextures, "Texture name generation is live.");
    coverage.markImplemented(FunctionId::glDeleteTextures, "Texture deletion is live.");
    coverage.markImplemented(FunctionId::glIsTexture, "Texture object query is live.");
    coverage.markImplemented(FunctionId::glBindTexture, "Texture binding is live.");
    coverage.markImplemented(FunctionId::glTexImage1D, "1D texture allocation/upload is live.");
    coverage.markImplemented(FunctionId::glTexImage2D, "2D texture allocation/upload is live.");
    coverage.markImplemented(FunctionId::glTexImage3D, "3D texture allocation/upload is live.");
    coverage.markImplemented(FunctionId::glTexSubImage1D, "1D texture subimage upload is live.");
    coverage.markImplemented(FunctionId::glTexSubImage2D, "2D texture subimage upload is live.");
    coverage.markImplemented(FunctionId::glTexSubImage3D, "3D texture subimage upload is live.");
    coverage.markImplemented(FunctionId::glTexParameteri, "Texture integer parameter state is live.");
    coverage.markImplemented(FunctionId::glTexParameteriv, "Texture integer parameter state is live.");
    coverage.markImplemented(FunctionId::glTexParameterf, "Texture float parameter state is live.");
    coverage.markImplemented(FunctionId::glTexParameterfv, "Texture float-vector parameter state is live.");
    coverage.markImplemented(FunctionId::glTexParameterIiv, "Texture integer-vector parameter state is live.");
    coverage.markImplemented(FunctionId::glTexParameterIuiv, "Texture unsigned integer-vector parameter state is live.");
    coverage.markImplemented(FunctionId::glGetTexParameteriv, "Texture integer parameter queries are live.");
    coverage.markImplemented(FunctionId::glGetTexParameterfv, "Texture float parameter queries are live.");
    coverage.markImplemented(FunctionId::glGetTexParameterIiv, "Texture integer parameter queries are live.");
    coverage.markImplemented(FunctionId::glGetTexParameterIuiv, "Texture unsigned parameter queries are live.");
    coverage.markImplemented(FunctionId::glGenerateMipmap, "Texture mipmap generation is live for Phase A texture storage.");
    coverage.markImplemented(FunctionId::glPixelStorei, "Integer pixel-store state is live.");
    coverage.markImplemented(FunctionId::glPixelStoref, "Float pixel-store state is live.");
    coverage.markImplemented(FunctionId::glReadBuffer, "Read-buffer state tracking is live.");
    coverage.markImplemented(FunctionId::glDrawBuffers, "MRT draw-buffer state tracking is live.");
    coverage.markImplemented(FunctionId::glIsRenderbuffer, "Renderbuffer object query is live.");
    coverage.markImplemented(FunctionId::glBindRenderbuffer, "Renderbuffer binding is live.");
    coverage.markImplemented(FunctionId::glDeleteRenderbuffers, "Renderbuffer deletion is live.");
    coverage.markImplemented(FunctionId::glGenRenderbuffers, "Renderbuffer name generation is live.");
    coverage.markImplemented(FunctionId::glRenderbufferStorage, "Renderbuffer storage allocation is live.");
    coverage.markImplemented(FunctionId::glGetRenderbufferParameteriv, "Renderbuffer parameter query is live.");
    coverage.markImplemented(FunctionId::glGenFramebuffers, "Framebuffer name generation is live.");
    coverage.markImplemented(FunctionId::glDeleteFramebuffers, "Framebuffer deletion is live.");
    coverage.markImplemented(FunctionId::glIsFramebuffer, "Framebuffer object query is live.");
    coverage.markImplemented(FunctionId::glBindFramebuffer, "Framebuffer read/draw binding is live.");
    coverage.markImplemented(FunctionId::glCheckFramebufferStatus, "Framebuffer completeness checks are live.");
    coverage.markImplemented(FunctionId::glFramebufferTexture1D, "1D texture framebuffer attachments are live.");
    coverage.markImplemented(FunctionId::glFramebufferTexture2D, "2D texture framebuffer attachments are live.");
    coverage.markImplemented(FunctionId::glFramebufferTexture3D, "3D texture framebuffer attachments are live.");
    coverage.markImplemented(FunctionId::glFramebufferRenderbuffer, "Renderbuffer framebuffer attachments are live.");
    coverage.markImplemented(FunctionId::glBlitFramebuffer, "CPU-shadowed framebuffer blits are live for color/depth/stencil masks (1:1 nearest).");
    coverage.markImplemented(FunctionId::glGetFramebufferAttachmentParameteriv, "Framebuffer attachment queries are live.");
    coverage.markImplemented(FunctionId::glRenderbufferStorageMultisample, "Multisample renderbuffer storage is live.");
    coverage.markImplemented(FunctionId::glFramebufferTextureLayer, "Layered texture framebuffer attachments are live.");
    coverage.markImplemented(FunctionId::glFramebufferTexture, "Whole-texture framebuffer attachments are live.");
    coverage.markImplemented(FunctionId::glGenSamplers, "Sampler name generation is live.");
    coverage.markImplemented(FunctionId::glDeleteSamplers, "Sampler deletion is live.");
    coverage.markImplemented(FunctionId::glIsSampler, "Sampler object query is live.");
    coverage.markImplemented(FunctionId::glBindSampler, "Texture-unit sampler binding is live.");
    coverage.markImplemented(FunctionId::glSamplerParameteri, "Sampler integer parameter state is live.");
    coverage.markImplemented(FunctionId::glSamplerParameteriv, "Sampler integer-vector parameter state is live.");
    coverage.markImplemented(FunctionId::glSamplerParameterf, "Sampler float parameter state is live.");
    coverage.markImplemented(FunctionId::glSamplerParameterfv, "Sampler float-vector parameter state is live.");
    coverage.markImplemented(FunctionId::glSamplerParameterIiv, "Sampler integer-vector parameter state is live.");
    coverage.markImplemented(FunctionId::glSamplerParameterIuiv, "Sampler unsigned integer-vector parameter state is live.");
    coverage.markImplemented(FunctionId::glGetSamplerParameteriv, "Sampler integer parameter queries are live.");
    coverage.markImplemented(FunctionId::glGetSamplerParameterfv, "Sampler float parameter queries are live.");
    coverage.markImplemented(FunctionId::glGetSamplerParameterIiv, "Sampler integer parameter queries are live.");
    coverage.markImplemented(FunctionId::glGetSamplerParameterIuiv, "Sampler unsigned parameter queries are live.");
    coverage.markImplemented(FunctionId::glEnable, "Enable-state tracking is live.");
    coverage.markImplemented(FunctionId::glDisable, "Enable-state tracking is live.");
    coverage.markImplemented(FunctionId::glIsEnabled, "Enable-state query is live.");
    coverage.markImplemented(FunctionId::glScissor, "Scissor-box tracking is live.");
    coverage.markImplemented(FunctionId::glDepthRange, "Depth-range tracking is live.");
    coverage.markImplemented(FunctionId::glDepthRangef, "Depth-range float alias is live.");
    coverage.markImplemented(FunctionId::glBlendFunc, "Blend function tracking is live.");
    coverage.markImplemented(FunctionId::glBlendFuncSeparate, "Separate blend function tracking is live.");
    coverage.markImplemented(FunctionId::glBlendEquation, "Blend equation tracking is live.");
    coverage.markImplemented(FunctionId::glBlendEquationSeparate, "Separate blend equation tracking is live.");
    coverage.markImplemented(FunctionId::glBlendColor, "Constant blend color tracking is live.");
    coverage.markImplemented(FunctionId::glColorMask, "Color write-mask tracking is live.");
    coverage.markImplemented(FunctionId::glColorMaski, "Indexed color write-mask tracking is live.");
    coverage.markImplemented(FunctionId::glDepthFunc, "Depth compare tracking is live.");
    coverage.markImplemented(FunctionId::glDepthMask, "Depth write-mask tracking is live.");
    coverage.markImplemented(FunctionId::glStencilFunc, "Stencil compare tracking is live.");
    coverage.markImplemented(FunctionId::glStencilFuncSeparate, "Separate stencil compare tracking is live.");
    coverage.markImplemented(FunctionId::glStencilOp, "Stencil operation tracking is live.");
    coverage.markImplemented(FunctionId::glStencilOpSeparate, "Separate stencil operation tracking is live.");
    coverage.markImplemented(FunctionId::glStencilMask, "Stencil write-mask tracking is live.");
    coverage.markImplemented(FunctionId::glStencilMaskSeparate, "Separate stencil write-mask tracking is live.");
    coverage.markImplemented(FunctionId::glCullFace, "Cull-face tracking is live.");
    coverage.markImplemented(FunctionId::glFrontFace, "Front-face winding tracking is live.");
    coverage.markImplemented(FunctionId::glPolygonOffset, "Polygon offset tracking is live.");
    coverage.markImplemented(FunctionId::glLineWidth, "Line-width tracking is live.");
    coverage.markImplemented(FunctionId::glPointSize, "Point-size tracking is live.");
    coverage.markImplemented(FunctionId::glHint, "Hint-state tracking is live.");
    coverage.markImplemented(FunctionId::glGetString, "Bootstrap identity reporting is live.");
    coverage.markImplemented(FunctionId::glGetError, "Bootstrap per-context error FIFO is live.");
    coverage.markImplemented(FunctionId::glDebugMessageControl, "Debug message filtering is live.");
    coverage.markImplemented(FunctionId::glDebugMessageInsert, "Debug message insertion is live.");
    coverage.markImplemented(FunctionId::glDebugMessageCallback, "Debug callback plumbing is live.");
    coverage.markImplemented(FunctionId::glGetDebugMessageLog, "Debug message log retrieval is live.");
    coverage.markImplemented(FunctionId::glPushDebugGroup, "Debug group push is live.");
    coverage.markImplemented(FunctionId::glPopDebugGroup, "Debug group pop is live.");
    coverage.markImplemented(FunctionId::glObjectLabel, "Debug object labels are live.");
    coverage.markImplemented(FunctionId::glGetObjectLabel, "Debug object-label queries are live.");
    coverage.markImplemented(FunctionId::glObjectPtrLabel, "Debug pointer labels are live.");
    coverage.markImplemented(FunctionId::glGetObjectPtrLabel, "Debug pointer-label queries are live.");
    coverage.markImplemented(FunctionId::glGetPointerv, "Debug pointer queries are live.");

    coverage.markImplemented(FunctionId::glCreateShader, "Shader objects are created with a stage tag.");
    coverage.markImplemented(FunctionId::glDeleteShader, "Shader objects are removed from the object store.");
    coverage.markImplemented(FunctionId::glIsShader, "Shader existence queries are live.");
    coverage.markImplemented(FunctionId::glShaderSource, "Shader source strings are stored.");
    coverage.markImplemented(FunctionId::glCompileShader, "Shader source is reflected for declarations.");
    coverage.markImplemented(FunctionId::glGetShaderiv, "Shader integer queries are live.");
    coverage.markImplemented(FunctionId::glGetShaderInfoLog, "Shader compile logs are queryable.");
    coverage.markImplemented(FunctionId::glGetShaderSource, "Stored shader source is queryable.");
    coverage.markImplemented(FunctionId::glCreateProgram, "Program objects are created in the object store.");
    coverage.markImplemented(FunctionId::glDeleteProgram, "Program objects are removed and unbound on delete.");
    coverage.markImplemented(FunctionId::glIsProgram, "Program existence queries are live.");
    coverage.markImplemented(FunctionId::glAttachShader, "Shader attachments are tracked per program.");
    coverage.markImplemented(FunctionId::glDetachShader, "Shader attachments are removable.");
    coverage.markImplemented(FunctionId::glLinkProgram, "Program link merges shader reflections.");
    coverage.markImplemented(FunctionId::glUseProgram, "Current program is tracked in the state mirror.");
    coverage.markImplemented(FunctionId::glValidateProgram, "Program validation status is tracked.");
    coverage.markImplemented(FunctionId::glGetProgramiv, "Program integer queries are live.");
    coverage.markImplemented(FunctionId::glGetProgramInfoLog, "Program info logs are queryable.");
    coverage.markImplemented(FunctionId::glGetAttachedShaders, "Attached shader names are enumerable.");
    coverage.markImplemented(FunctionId::glBindAttribLocation, "Pre-link attribute location requests are honored.");
    coverage.markImplemented(FunctionId::glGetAttribLocation, "Vertex attribute locations are queryable post-link.");
    coverage.markImplemented(FunctionId::glGetActiveAttrib, "Active vertex attribute reflection is live.");
    coverage.markImplemented(FunctionId::glGetUniformLocation, "Uniform locations are queryable post-link.");
    coverage.markImplemented(FunctionId::glGetActiveUniform, "Active uniform reflection is live.");
    coverage.markImplemented(FunctionId::glGetUniformfv, "Uniform float readback is live.");
    coverage.markImplemented(FunctionId::glGetUniformiv, "Uniform integer readback is live.");
    coverage.markImplemented(FunctionId::glGetUniformuiv, "Uniform unsigned integer readback is live.");
    coverage.markImplemented(FunctionId::glUniform1f, "Float scalar uniforms are live.");
    coverage.markImplemented(FunctionId::glUniform2f, "Float vec2 uniforms are live.");
    coverage.markImplemented(FunctionId::glUniform3f, "Float vec3 uniforms are live.");
    coverage.markImplemented(FunctionId::glUniform4f, "Float vec4 uniforms are live.");
    coverage.markImplemented(FunctionId::glUniform1i, "Int scalar uniforms are live.");
    coverage.markImplemented(FunctionId::glUniform2i, "Int vec2 uniforms are live.");
    coverage.markImplemented(FunctionId::glUniform3i, "Int vec3 uniforms are live.");
    coverage.markImplemented(FunctionId::glUniform4i, "Int vec4 uniforms are live.");
    coverage.markImplemented(FunctionId::glUniform1ui, "Unsigned scalar uniforms are live.");
    coverage.markImplemented(FunctionId::glUniform2ui, "uvec2 uniforms are live.");
    coverage.markImplemented(FunctionId::glUniform3ui, "uvec3 uniforms are live.");
    coverage.markImplemented(FunctionId::glUniform4ui, "uvec4 uniforms are live.");
    coverage.markImplemented(FunctionId::glUniform1fv, "Float scalar uniform arrays are live.");
    coverage.markImplemented(FunctionId::glUniform2fv, "vec2 uniform arrays are live.");
    coverage.markImplemented(FunctionId::glUniform3fv, "vec3 uniform arrays are live.");
    coverage.markImplemented(FunctionId::glUniform4fv, "vec4 uniform arrays are live.");
    coverage.markImplemented(FunctionId::glUniform1iv, "Int scalar uniform arrays are live.");
    coverage.markImplemented(FunctionId::glUniform2iv, "ivec2 uniform arrays are live.");
    coverage.markImplemented(FunctionId::glUniform3iv, "ivec3 uniform arrays are live.");
    coverage.markImplemented(FunctionId::glUniform4iv, "ivec4 uniform arrays are live.");
    coverage.markImplemented(FunctionId::glUniform1uiv, "uint scalar uniform arrays are live.");
    coverage.markImplemented(FunctionId::glUniform2uiv, "uvec2 uniform arrays are live.");
    coverage.markImplemented(FunctionId::glUniform3uiv, "uvec3 uniform arrays are live.");
    coverage.markImplemented(FunctionId::glUniform4uiv, "uvec4 uniform arrays are live.");
    coverage.markImplemented(FunctionId::glUniformMatrix2fv, "mat2 uniforms are live.");
    coverage.markImplemented(FunctionId::glUniformMatrix3fv, "mat3 uniforms are live.");
    coverage.markImplemented(FunctionId::glUniformMatrix4fv, "mat4 uniforms are live.");
    coverage.markImplemented(FunctionId::glDrawArrays, "Solid-color draw path (Phase A Group 7 MVP).");
    coverage.markImplemented(FunctionId::glDrawElements, "Solid-color indexed draw path (Phase A Group 7 MVP).");
    // Phase 4 Pass A — GL 4.0/4.1 state-only additions.
    coverage.markImplemented(FunctionId::glPatchParameteri, "Tessellation patch vertex count state tracked.");
    coverage.markImplemented(FunctionId::glPatchParameterfv, "Tessellation default outer/inner levels tracked.");
    coverage.markImplemented(FunctionId::glBeginQueryIndexed, "Indexed query begin stub (CPU-only).");
    coverage.markImplemented(FunctionId::glEndQueryIndexed, "Indexed query end stub (CPU-only).");
    coverage.markImplemented(FunctionId::glGetQueryIndexediv, "Indexed query get stub returns defaults.");
    coverage.markImplemented(FunctionId::glViewportArrayv, "Per-viewport-index array state tracked.");
    coverage.markImplemented(FunctionId::glViewportIndexedf, "Per-viewport-index state tracked.");
    coverage.markImplemented(FunctionId::glViewportIndexedfv, "Per-viewport-index state tracked.");
    coverage.markImplemented(FunctionId::glScissorArrayv, "Per-scissor-index array state tracked.");
    coverage.markImplemented(FunctionId::glScissorIndexed, "Per-scissor-index state tracked.");
    coverage.markImplemented(FunctionId::glScissorIndexedv, "Per-scissor-index state tracked.");
    coverage.markImplemented(FunctionId::glDepthRangeArrayv, "Per-depth-range-index array state tracked.");
    coverage.markImplemented(FunctionId::glDepthRangeIndexed, "Per-depth-range-index state tracked.");
    coverage.markImplemented(FunctionId::glGetFloati_v, "Indexed float state query returns tracked values.");
    coverage.markImplemented(FunctionId::glGetDoublei_v, "Indexed double state query returns tracked values.");
    coverage.markImplemented(FunctionId::glClearDepthf, "Float-precision depth clear state tracked.");
    coverage.markImplemented(FunctionId::glGetShaderPrecisionFormat, "Shader precision query returns Metal-appropriate ranges.");

    // Phase A Group 8: wire the remaining <=3.3 entry points so the dispatch
    // table has no unimplementedReturn<> fallback for any manifest function in
    // the promotion-gate window. Queries are live; everything else ships as a
    // minimal no-op stub until a dedicated scenario lights it up.
    installGroup8Dispatch(dispatch, coverage);
}

}  // namespace appgl
